# DCS Site Configuration
# This file configures the integration between this site and DCS Portal

site_slug: demo-2
site_name: Vue Demo Site
storage_account: stdemositetwo
output_location: dist

# Site hosting (static blob storage for demo sites)
production_url: https://stdemositetwo.z22.web.core.windows.net/
